name: Create Github Release
on:
  pull_request:
    types: [closed]
    branch: main
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run release
      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: git push --follow-tags origin main
      - run: npm run build
      - name: Get version from package-lock.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package-lock.json').version")"
      - name: Get changelog
        run: |
          CHANGELOG=$(tail -n +$(grep -n "## \[v${{ steps.get_version.outputs.version }}\]" CHANGELOG.md | cut -d ":" -f 1) CHANGELOG.md)
          echo "::set-output name=changelog::${CHANGELOG}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          release_name: "v${{ steps.get_version.outputs.version }}"
          body: ${{ steps.get_changelog.outputs.changelog }}