name: Create Github Release
on:
  pull_request:
    types: [closed]
    branch: main
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Set up git user for release
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - run: npm run release
      - name: Push changes
        run: git push --follow-tags origin main
      - run: npm run build
      - name: Get version from package-lock.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package-lock.json').version")"
      - name: Get changelog
        run: |
          CHANGELOG=$(awk '/^### \[[0-9]+\.[0-9]+\.[0-9]+\]/{if (version!="") {exit}; version=$2} version!="" {print}' CHANGELOG.md)
          echo "::set-output name=changelog::${CHANGELOG}"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          release_name: "v${{ steps.get_version.outputs.version }}"
          body: ${{ steps.get_changelog.outputs.changelog }}
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: frontend
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://raw.githubusercontent.com/birdwingo/react-native-reanimated-graph/main/src/assets/images/logo.png
        SLACK_MESSAGE: New Release ${{ steps.get_version.outputs.version }} ${{ job.status == 'success' && 'has been created' || 'has been failed' }}
        SLACK_TITLE: Graph release :rocket:
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}