name: Create Github Release
on:
  pull_request:
    types: [closed]
    branch: main
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Set up git user for release
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - run: npm run release
      - run: npm run build
      - name: Get version from package-lock.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package-lock.json').version")"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          release_name: "v${{ steps.get_version.outputs.version }}"